const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
const GET_POKEMON_DETAILS = 'GET_POKEMON_DETAILS';
const GET_TYPES = 'GET_TYPES';
const SET_PER_PAGE = 'SET_PER_PAGE';
const SET_PKMNS_STATS = 'SET_PKMNS_STATS';
const FILTER_BY_ORIGIN_API = 'FILTER_BY_ORIGIN_API';
const FILTER_BY_ORIGIN_USER = 'FILTER_BY_ORIGIN_USER';
const FILTER_BY_TYPE = 'FILTER_BY_TYPE';

const SERVER_URL = 'https://pokedex-back-jv.herokuapp.com';
const LIMIT = 500;

export {
    GET_ALL_POKEMONS,
    GET_POKEMON_DETAILS,
    GET_TYPES,
    SET_PKMNS_STATS,
    SET_PER_PAGE,
    FILTER_BY_ORIGIN_API,
    FILTER_BY_ORIGIN_USER,
    FILTER_BY_TYPE,
    SERVER_URL,
    LIMIT,
};
